version: '3.8'
name: avito-backend-trainee
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /pgdata:/var/lib/postgresql/data
    restart: always

  server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis